trigger:
  - main

pool:
  name: devops-agent

variables:
  terraformVersion: '1.14.6'
  workingDirectory: '$(System.DefaultWorkingDirectory)/environment'

stages:
  - stage: Terraform_Init_Validate_Plan
    displayName: 'Terraform Init Validate Plan'

    jobs:
      - job: TerraformPlan
        displayName: 'Terraform Plan'

        steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: 'Terraform Installer'
            inputs:
              terraformVersion: '$(terraformVersion)'

          - script: |
              terraform init
            displayName: 'Terraform Init'
            workingDirectory: '$(workingDirectory)'

          - script: |
              terraform validate
            displayName: 'Terraform Validate'
            workingDirectory: '$(workingDirectory)'

          - script: |
              terraform plan
            displayName: 'Terraform Plan'
            workingDirectory: '$(workingDirectory)'