trigger:
  - main

pool:
  name: devops-agent

variables:
  terraformVersion: '1.14.6'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

stages:
  - stage: Terraform_Init_Validate_Plan
    displayName: 'Terraform Init Validate Plan'

    jobs:
      - job: TerraformPlan
        displayName: 'Terraform Plan'

        steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: 'Terraform Installer'
            inputs:
              terraformVersion: '$(terraformVersion)'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(workingDirectory)'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Validate'
            inputs:
              provider: 'azurerm'
              command: 'validate'
              workingDirectory: '$(workingDirectory)'

          - task: TerraformTaskV4@4
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(workingDirectory)'
              environmentServiceNameAzureRM: 'azure-terraform-connection'